FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

RUN mkdir -p /app/data

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["sh", "-c", "python /app/scripts/init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]